run:
  deadline: 1m
  tests: true

linters:
  enable-all: true

linters-settings:
  gocyclo:
    min-complexity: 11
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.25  # ignore missing package comment false positive
